[package]
name = "mccfind"
description = "Find Google Ads accounts with matching criteria within Google MCC Manager Account"
version = "0.1.0"
authors = ["Michael S. Huang <mhuang74@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.6", features = ["derive", "cargo"] }
futures = { version = "0.3", default-features = false, features = ["alloc"] }
googleads-rs = { path = "../googleads-rs" }
itertools = "0.10"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1.0", features = [ "rt-multi-thread", "time", "fs", "macros", "net",] }
tokio-stream = { version = "0.1", features = ["net"] }
tonic = { version = "0.6.2", features = ["tls", "tls-roots"] }
serde_json = "1.0.79"
yup-oauth2 = "6.3.1"