[package]
name = "mcc-gaql"
description = "Execute GAQL across MCC child accounts."
version = "0.3.0"
authors = ["Michael S. Huang <mhuang74@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anomaly_detection = "0.2"
anyhow = "1.0.56"
async-std = "1.11.0"
bincode = "1.3.3"
cacache = "10.0.1"
clap = { version = "3.1.6", features = ["derive", "cargo"] }
dirs = "4.0.0"
figment = { version = "0.10.6", features = ["toml", "env"] }
flexi_logger = { version = "0.22", features = ["compress"] }
futures = { version = "0.3", default-features = false, features = ["alloc"] }
googleads-rs = { version = "0.3.0", path="../googleads-rs" }
itertools = "0.10"
log = "0.4"
polars = "0.21.1"
serde = { version = "1.0.136", features = ["derive"] }
thousands = "0.2.0"
tokio = { version = "1.0", features = [ "rt-multi-thread", "time", "fs", "macros", "net",] }
tokio-stream = { version = "0.1", features = ["net"] }
toml = "0.5.8"
tonic = { version = "0.7.2", features = ["tls", "tls-roots"] }
serde_json = "1.0.79"
yup-oauth2 = "6.7.1"