[package]
name = "gaql-cli"
version = "0.1.0"
authors = ["Michael S. Huang <mhuang74@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = { version = "0.3", default-features = false, features = ["alloc"] }
tokio = { version = "1.0", features = [ "rt-multi-thread", "time", "fs", "macros", "net",] }
tokio-stream = { version = "0.1", features = ["net"] }
tonic = { version = "0.6.2", features = ["tls", "tls-roots"] }
gapi_grpc = { path = "../gapi-grpc-rs" }
yup-oauth2 = "6.3.1"
