###
#
# GAQL Query Cookbook
#
# Michael S. Huang (mhuang74@gmail.com)
#
##

# Accessible Trafficking Accounts
account_accessible = """
	SELECT 
	  customer.id, 
	  metrics.clicks 
	FROM customer 
	WHERE 
	  segments.date during yesterday
	  and metrics.impresisons > 1
	ORDER BY
		customer.id
"""

# Total Account Traffic Last Week
account_traffic_yesterday = """
	SELECT 
	  customer.id, 
	  customer.descriptive_name, 
	  metrics.impressions, 
	  metrics.clicks, 
	  metrics.cost_micros 
	FROM customer 
	WHERE 
	  segments.date during yesterday
"""

# Top Keywords
top_keywords_last_week = """
	SELECT
	  customer.id,
	  customer.descriptive_name,
	  campaign.id,
	  campaign.name,
	  campaign.advertising_channel_type,
	  ad_group.id,
	  ad_group.name,
	  ad_group.type,
	  ad_group_criterion.criterion_id,
	  ad_group_criterion.keyword.text,
	  metrics.impressions,
	  metrics.clicks,
	  metrics.cost_micros
	FROM keyword_view
	WHERE
	  segments.date DURING LAST_7_DAYS
	  and metrics.clicks > 10000
	ORDER BY
	  metrics.clicks DESC
	LIMIT 10
"""

# Accounts with Performance Max Campaigns
account_perf_max_campaigns_last_week = """
	SELECT 
	  customer.id, 
	  customer.descriptive_name, 
	  campaign.id, 
	  campaign.advertising_channel_type, 
	  campaign.name, 
	  metrics.impressions, 
	  metrics.clicks, 
	  metrics.cost_micros,
	  customer.currency_code 
	FROM campaign 
	WHERE 
	  segments.date DURING LAST_7_DAYS 
	  AND campaign.advertising_channel_type IN ('PERFORMANCE_MAX') 
	  AND metrics.clicks > 100
	ORDER BY 
	  metrics.clicks DESC 
	LIMIT 1
"""

# Accounts with Smart Campaigns
account_smart_campaigns_last_week = """
	SELECT 
	  customer.id, 
	  customer.descriptive_name, 
	  campaign.id, 
	  campaign.advertising_channel_type, 
	  campaign.name, 
	  metrics.impressions, 
	  metrics.clicks, 
	  metrics.cost_micros,
	  customer.currency_code 
	FROM campaign 
	WHERE 
	  segments.date DURING LAST_7_DAYS 
	  AND campaign.advertising_channel_type IN ('SMART') 
	  AND metrics.clicks > 100
	ORDER BY 
	  metrics.clicks DESC 
	LIMIT 1
"""

# Accounts with Local Campaigns
account_local_campaigns_last_week = """
	SELECT 
	  customer.id, 
	  customer.descriptive_name, 
	  campaign.id, 
	  campaign.advertising_channel_type, 
	  campaign.name, 
	  metrics.impressions, 
	  metrics.clicks, 
	  metrics.cost_micros,
	  customer.currency_code 
	FROM campaign 
	WHERE 
	  segments.date DURING LAST_7_DAYS 
	  AND campaign.advertising_channel_type IN ('LOCAL') 
	  AND metrics.clicks > 500
	ORDER BY 
	  metrics.clicks DESC 
	LIMIT 1
"""

# Accounts with Shopping Campaigns
account_shopping_campaigns_last_week = """
	SELECT 
	  customer.id, 
	  customer.descriptive_name, 
	  campaign.id, 
	  campaign.advertising_channel_type, 
	  campaign.name, 
	  metrics.impressions, 
	  metrics.clicks, 
	  metrics.cost_micros,
	  customer.currency_code 
	FROM campaign 
	WHERE 
	  segments.date DURING LAST_7_DAYS 
	  AND campaign.advertising_channel_type IN ('SHOPPING') 
	  AND metrics.clicks > 100
	ORDER BY 
	  metrics.clicks DESC 
	LIMIT 1
"""

# Accounts with Multi-Channel Campaigns
account_multichannel_campaigns_last_week = """
	SELECT 
	  customer.id, 
	  customer.descriptive_name, 
	  campaign.id, 
	  campaign.advertising_channel_type, 
	  campaign.name, 
	  metrics.impressions, 
	  metrics.clicks, 
	  metrics.cost_micros,
	  customer.currency_code 
	FROM campaign 
	WHERE 
	  segments.date DURING LAST_7_DAYS 
	  AND campaign.advertising_channel_type IN ('MULTI_CHANNEL') 
	  AND metrics.clicks > 100
	ORDER BY 
	  metrics.clicks DESC 
	LIMIT 1
"""


# Accounts with Asset-based Sitelink Ext
account_asset_sitelink_last_week = """
	SELECT 
	  customer.id, 
	  customer.descriptive_name, 
	  campaign.id, 
	  campaign.advertising_channel_type, 
	  campaign.name, 
	  asset_field_type_view.field_type, 
	  metrics.impressions, 
	  metrics.clicks, 
	  metrics.cost_micros,
		customer.currency_code  
	FROM asset_field_type_view 
	WHERE 
	  segments.date DURING LAST_7_DAYS 
	  AND asset_field_type_view.field_type IN ('SITELINK') 
	  AND metrics.clicks > 20000
	ORDER BY 
	  metrics.impressions DESC 
	LIMIT 1
"""

# Accounts with Asset-based Call Ext
account_asset_call_last_week = """
	SELECT 
	  customer.id, 
	  customer.descriptive_name, 
	  campaign.id, 
	  campaign.advertising_channel_type, 
	  campaign.name, 
	  asset_field_type_view.field_type, 
	  metrics.impressions, 
	  metrics.clicks, 
	  metrics.cost_micros,
		customer.currency_code  
	FROM asset_field_type_view 
	WHERE 
	  segments.date DURING LAST_7_DAYS 
	  AND asset_field_type_view.field_type IN ('CALL') 
	  AND metrics.impressions > 100
	ORDER BY 
	  metrics.impressions DESC 
	LIMIT 1
"""

# Accounts with Asset-based Callout Ext
account_asset_callout_last_week = """
	SELECT 
	  customer.id, 
	  customer.descriptive_name, 
	  campaign.id, 
	  campaign.advertising_channel_type, 
	  campaign.name, 
	  asset_field_type_view.field_type, 
	  metrics.impressions, 
	  metrics.clicks, 
	  metrics.cost_micros,
	  customer.currency_code  
	FROM asset_field_type_view 
	WHERE 
	  segments.date DURING LAST_7_DAYS 
	  AND asset_field_type_view.field_type IN ('CALLOUT') 
	  AND metrics.clicks > 30000
	ORDER BY 
	  metrics.impressions DESC 
	LIMIT 1
"""

# Accounts with Asset-based App Ext
account_asset_app_last_week = """
	SELECT 
	  customer.id, 
	  customer.descriptive_name, 
	  campaign.id, 
	  campaign.advertising_channel_type, 
	  campaign.name, 
	  asset_field_type_view.field_type, 
	  metrics.impressions, 
	  metrics.clicks, 
	  metrics.cost_micros,
		customer.currency_code  
	FROM asset_field_type_view 
	WHERE 
	  segments.date DURING LAST_7_DAYS 
	  AND asset_field_type_view.field_type IN ('MOBILE_APP') 
	  AND metrics.impressions > 1
	ORDER BY 
	  metrics.impressions DESC 
	LIMIT 1
"""

# Last 30-day Traffic from Performance Max Campaigns
campaign_perf_max_campaigns_30_days = """
	SELECT 
	  campaign.id, 
	  segments.date,
	  metrics.impressions, 
	  metrics.clicks, 
	  metrics.cost_micros,
	  customer.currency_code 
	FROM campaign 
	WHERE 
	  segments.date DURING LAST_30_DAYS 
	  AND campaign.advertising_channel_type IN ('PERFORMANCE_MAX')
	  AND metrics.impressions > 1 
	ORDER BY 
	  segments.date, campaign.id
"""