account_traffic_yesterday = """
	SELECT 
	  customer.id, 
	  customer.descriptive_name, 
	  metrics.impressions, 
	  metrics.clicks, 
	  metrics.cost_micros 
	FROM customer 
	WHERE 
	  segments.date during yesterday
"""

top_10_keywords_last_week = """
	SELECT
	  customer.id,
	  customer.descriptive_name,
	  campaign.id,
	  campaign.name,
	  campaign.advertising_channel_type,
	  ad_group.id,
	  ad_group.name,
	  ad_group.type,
	  ad_group_criterion.criterion_id,
	  ad_group_criterion.keyword.text,
	  metrics.impressions,
	  metrics.clicks,
	  metrics.cost_micros
	FROM keyword_view
	WHERE
	  segments.date DURING LAST_7_DAYS
	  and metrics.clicks > 10000
	ORDER BY
	  metrics.clicks DESC
	LIMIT 10
"""

top_perf_max_campaigns_last_week = """
SELECT 
  customer.id, 
  customer.descriptive_name, 
  campaign.id, 
  campaign.advertising_channel_type, 
  campaign.name, 
  metrics.impressions, 
  metrics.clicks, 
  metrics.cost_micros,
  customer.currency_code 

FROM campaign 
WHERE 
  segments.date DURING LAST_7_DAYS 
  AND campaign.advertising_channel_type IN ('PERFORMANCE_MAX') 
  AND metrics.clicks > 100
ORDER BY 
  metrics.clicks DESC 
LIMIT 10 
"""
